BV-BRC/BV-BRC-Web

- public/js/p3/resources/bv-brc.css
- views/bv-brc-header.ejs
- views/home.ejs
This PR adds the search bar to the main BV-BRC section. It also adds the browse buttons section.
This PR also fixes some layout issues at tablet and smaller resolutions. It’s not perfect but works for what’s here at the moment. I originally wanted to have a nice mobile view but cannot without really thinking through how to modify the navigation menu at smaller resolutions because we have too much content in the menu bar. Some aspects would need to be hidden. The navigation menu needs further discussion. 
On resolutions 990px and smaller the layout consists of a now, non-broken two column grid and remains in this format.
**desktop**
**tablet or smaller**
> Homepage content, search and layout

- public/js/p3/widget/ColumnsGenome.js
- public/js/p3/widget/DataItemFormatter.js
This pull request adds and removes genome solr fields from the genome view page, genomes tab sidebar, and + columns menu.
**Added to Genome View Page / Genomes Tab Sidebar**
* other_names
* season
* host_common_name
**Added to + columns menu**
* other_names
* authors
* segments
* mat_peptide
* season
* host_common_name
**Removed from Genome View Page / Genomes Tab Sidebar**
* refseq_accessions
* sequencing_status
* patric_cds
* refseq_cds
* isolation_site
* latitude
* longitude
* altitude
* depth
* body_sample_site
* body_sample_subsite
* antimicrobial_resistance
**Removed from + columns menu**
* refseq_accessions
* sequencing_status
* patric_cds
* refseq_cds
* isolation_site
* latitude
* longitude
* altitude
* depth
* body_sample_site
* body_sample_subsite
* antimicrobial_resistance
* …
> Add/Remove Genome Solr elements from website

- public/js/p3/widget/GenomeBrowser.js
- public/js/p3/widget/viewer/VariantLineage.js
Just two small changes -- one adds MultiBigWig to the plugins list in Genome Browser and the other adds a default view to the displayed page.   These changes go with a PR I just did to PATRIC/p3_api bv-brc branch and the default view will break unless the p3_api PR is already done.  Thanks.
> Updates for SARS-COV-2 Variants and Lineages of Concern

- public/js/p3/widget/viewer/ProteinStructure.js
Given that we haven't been able to solve the performance issues when using Safari, add note to viewer for Safari users recommending the chrome browser.
> Add note for Safari users recommending Chrome

- public/js/p3/widget/app/PrimerDesign.js
Submitting json with OUTPUT_PATH and OUTPUT_FILE caused the job submission to not recognize the output folder. Switched them to lowercase, output_path and output_file, fixes this issue.
> Primer design UI update: modifying json parameters

- public/js/p3/widget/app/Assembly2.js
Named an attribute wrong which conflicted with the required output_path attribute. Changed my attribute to the appropriate name
> Fixed bug in Assembly2.js

- public/js/p3/resources/GridStyle.css
- public/js/p3/widget/ColumnHider.js
- public/js/p3/widget/Grid.js
- public/js/p3/widget/PageGrid.js
Here is the custom column hider code.  Note that this code doesn't actually define/redefine any of the grouping for individual grids to take advantage of this code.  It will, however, by default, alphabetize the columns instead of displaying them in the order they are in the table.
> Feature custom column selector

- public/js/p3/widget/app/AppBase.js
- public/js/p3/widget/app/FastqUtil.js
- public/js/p3/widget/app/Rnaseq.js
- public/js/p3/widget/app/Variation.js
when a user submits multiple jobs without reloading the page or equivalent the library would contain duplicate entries. Fix resets these libraries on submission
> Fix for duplicated library entries 

- public/js/archaeopteryx/archaeopteryx-dependencies/archaeopteryx.js
- public/js/bundle/bundle2.js
- public/js/p3/widget/Phylogeny2.js
This change requires Archaeopteryx submodule update to v 2.0.0a4 (2022-03-15) version and bundle2.js rebuild.
> Enabled Archaeopteryx tree to order sister-clades and turn on internal labels prior to tree display

- public/js/p3/widget/app/FastqUtil.js
This fixes the reset button for fastq-utils. Libraries and pipelines weren't being cleared.
This fixes https://github.com/BV-BRC/issues/issues/672.
It is related to https://github.com/BV-BRC/issues/issues/347.
> Reset the memory stores for libraries and conditions.

- public/js/p3/widget/IDMappingGrid.js
- public/js/p3/widget/app/MetagenomicBinning.js
For some reason PageGrid.js is calling createStore() in widget/IDMappingGrid.js by passing the primaryKey (sorting) as the auth token <through inheritance>.
Fixes https://github.com/BV-BRC/issues/issues/752
> fixing PageGrid.js passing primaryKey as token

- public/js/p3/widget/CompareRegionContainer.js
- public/js/p3/widget/CompareRegionViewer.js
- public/js/p3/widget/PerspectiveToolTip.js
- public/js/p3/widget/viewer/Feature.js
- public/js/p3/widget/viewer/FeatureGroup.js
- public/js/p3/widget/viewer/_FeatureList.js
Note - this turns compare regions back on for viruses since it is now useful with the large DNA viruses.
We also add compare regions to the feature list and feature group pages.
> Update for compare regions 

- public/js/p3/widget/WorkspaceBrowser.js
- public/js/p3/widget/viewer/JobResult.js
- public/js/p3/widget/viewer/SeqComparison.js
Currently if a job was run by a user in a private workspace and copied to public, the job would not view properly.
This PR causes the job result list to be edited on load to point at the correct location.
> Fix view of jobs that were copied into public workspace

- public/js/p3/WorkspaceManager.js
- public/js/p3/widget/GlobalSearch.js
- public/js/p3/widget/templates/GlobalSearch.html
Change the behavior of global search:
Add an option Feature ID Match that looks for strings in the query that match feature IDs, and
drive the browser directly to either the feature page, if a single feature was selected,
or to the feature list page configured with the set of features.
Add an option Genome ID Match that looks for strings in the query that match genome IDs, and
drive the browser directly to either the genome page, if a single genome was selected,
or to the genome list page configured with the set of genomes.
If neither of these options was selected, but the query text includes either a feature ID or a
genome ID, act as if the Feature ID Match or Genome ID Match option was selected.
> Change behavior of global search for IDs (Not yet for production)

- public/js/p3/app/p3app.js
- public/js/p3/widget/Grid.js
- public/js/p3/widget/GridCopyToClipboard.js
- public/js/p3/widget/PageGrid.js
- public/js/p3/widget/SuLogin.js
Support ctrl-c / command-c to copy items from grids.  Always includes header and only copies visible columns. Fixes #527.
> allow keyboard ctrl-c or command-c to copy selected items

- public/js/p3/widget/viewer/GenomeList.js
Fixes #441.  Applies global filter when clicking apply.
> Fix apply filter on the GenomeList view

- public/js/p3/widget/ActionBar.js
- public/js/p3/widget/CopyTooltipDialog.js
- public/js/p3/widget/GridContainer.js
- public/js/p3/widget/WorkspaceBrowser.js
- public/js/p3/widget/viewer/TSV_CSV.js
1. Renamed an action panel button to COPY ROWS to distinguish it from COPY.
2. Got it to work for generic TSV viewers by adding a '' (empty) type.
3. Changed the description of the drop down items to refer to copying columns, since that is where the items differ. This avoids confusion, since I was confused by it.
> COPY ROWS for tsv viewer. Changed descriptions.

- public/js/p3/store/HomologyResultMemoryStore.js
- public/js/p3/widget/HomologyResultGrid.js
Using BLAST against a FASTA file that had no patric ids or genome ids was not displaying in the Homology viewer.
I fixed this so that FASTA files with no recognizable ids can be displayed in the viewer.
> Allow rendering BLAST results without pids or gids.

- public/js/p3/widget/app/templates/Homology.html
- public/js/p3/widget/app/templates/MSA.html
This change was done with the Homology service and the MSA service.
> Trigger fasta seqs input validation with onChange

- .gitmodules
- public/js/bundle/bundle2.js
- public/js/p3/widget/VariantLineagePhlyogenyTreeViewer.js
This PR contains a few things for Arachaeopteryx.
1. First, tracking for the submodule has been set to its master branch as it had been stuck on a detached head. This kept some aspects from updating when I thought it had been. It’s been fast forwarded and new updates/commits added to the submodule. I will point alpha, beta, and production to the correct tracking branch so that git doesn’t report differences when updates are pulled down onto each instance.
2. The newest data XML file, iteration 21, has been copied over to be served from the data api. 
3. VariantLineagePhlyogenyTreeViewer.js updated to reference newest data file.
4. VariantLineagePhlyogenyTreeViewer.js also includes changes that need to be manually applied from voc_example.html / outlined in the email requesting an update. …
> Arachaeopteryx.js updates

- public/js/p3/widget/app/AppBase.js
Always parse XML in code instead of deferring to the xhr handler. Replace index-based parsing of the XML with xpath queries. If an experiment ID is passed, fill in the run IDs within that experiment.
> SRA validation fixes

- views/pages/team.ejs
Thought I could go ahead and take care of this one myself. The label 'enhancement' seemed to be the only one that fit at the moment though a tad cheeky I'd say.
> sudo userdel --force ccthomas@anl.gov

- public/js/p3/widget/app/templates/PrimerDesign.html
Issue: https://github.com/BV-BRC/issues/issues/1122
Using standard id attributes can cause conflicts in the routing system. The widget tries to create itself again but can't since the id is hard coded in the html template.
Relying on the dojo-attach-points is safer or incrementing the id attribute with a counter if you have to. In this case the .js file relies on the dojo attribute anyway.
@mshukla1 you may want to make mention of this for devs to be aware of. The MSA.html template has an incrementing example from @JacobPorter as well.
> Fix widget conflict on Primer Design

- public/js/p3/widget/app/AppBase.js
- public/js/p3/widget/app/TaxonomicClassification.js
- public/js/p3/widget/viewer/File.js
Hello Bob,
I made a small change to the taxonomic classification service .JS. I tried to remove R1 from sample ID but it as problematic with SRR#'s. I'm open to more robust solutions here.  File.JS has changes from Dustin to address the iframe issue described in [issue 1165](https://github.com/BV-BRC/issues/issues/1165). I went through my outputs (mostly from testing the rerun button) and didn't see any issues. But I would echo Dustin's comment in the meeting today to say that we should ask people to test their .HTML outputs to ensure they are not impacted by this change. 
Nicole
> Changes related to output files for taxonomic classification service

- public/js/p3/widget/app/templates/MetagenomicReadMapping.html
- public/js/p3/widget/app/templates/TaxonomicClassification.html
Hello Bob, 
I changed the app box widths to be the same size for all the app boxes.
I changed the title of the host genome drop down to filter host genome and adding 'no host' option according to changes in BV-BRC Taxonomic Classification 2 in commit: 92017b754cb8c90d6e6902dc6c14d0c5214150e3.
> adding 'no host' option and fixing widths

- public/js/p3/widget/app/Tnseq.js
- public/js/p3/widget/app/templates/Tnseq.html
like RNASeq, users could submit jobs without the required number of conditions for the resampling strategy which performs contrasts. This disables the submit button until one treatment and one control is added to the library store when resampling is selected
> Alpha clark tnseq UI

- public/js/p3/widget/app/templates/TaxonomicClassification.html
Hello,
I updated the default options by moving the default to the top of the list in the TaxonomicClassification.HTML file. Is there a better way to do this?
After emptying the cash and a hard reload I was unable to recreate the behavior of the invalid SRA Run Accession on alpha or in my local host- no changes were made regarding that error. I don't think we need any.
Let me know what you think about the default option or if you have any questions,
Nicole
> Update default options for TaxonomicClassification.html

- public/js/p3/widget/app/FastqUtil.js
- public/js/p3/widget/app/templates/FastqUtil.html
- public/js/p3/widget/app/templates/TaxonomicClassification.html
Hello Bob,
This pull request should address the following:
- remove the commented out code block from commit: 4e87d1ae84f8230ff8869020dc6a1ff3057f93ee
- conclude the fix to the Fastq Utils "i" icon
- address/improve the box alignment
The docs are already updated in BV-BRC-Docs PR: [12](https://github.com/BV-BRC/BV-BRC-Docs/pull/112).
Kind regards,
Nicole
> Fix to the commented code from the fastq utils edits

- public/js/p3/widget/app/PhylogeneticTree.js
- Changing the default codon tree metadata to genome_id, genome_name, strain, isolation_country, host_common_name, and collection_year
> Updated Default Codon Tree metadata

- public/js/p3/widget/app/templates/Expression.html
- The values for NCBI Gene ID and NCBI GI Number were not correct: NCBI Gene ID was set to an integer field when it should be a string, NCBI GI Number to an integer field mapped to a different field
- Updated NCBI Gene ID -> 'gene' (string)
- Updated NCBI GI Number -> 'gene_id' (integer)
> fixing NCBI Gene ID and NCBI GI Number dropdown values

- public/js/p3/widget/viewer/PathwayMap.js
- Authorization header was lacking from pathways map genome query, resulting in empty PathwayMap views for private genomes
- Adding authorization header enables the view as expected
- A limit value was not present in the genome pathway map query which restricted the returned data
- Adding a limit and setting it arbitrarily high has removed this problem
> Adding authorization headers and removing limit from pathways map query

- public/js/p3/widget/StructureIdSelector.js
- public/js/p3/widget/app/templates/Docking.html
Hello,
This pull request encompasses the following:
- addition of a Exemplar drug compounds to be used in workshops and as examples
- makes all fields the same length across the page
- reorders the input options with the ligand database as default
These changes have been tested and are ready to be further tested on alpha.
Kind regards,
Nicole
> Add Exemplar database and fix spacing across form

- views/pages/team.ejs
this PR removes JCVI personnel who are no longer active on the project.
> Update to JCVI personnel
