views/javascript.ejs
This reverts commit f273fcc927ed6de5d7f6ae2f3886a054e8b76db6.
=> Revert "Disable PATRIC Google Analytics"

public/js/p3/widget/DataItemFormatter.js
Add missing 'authors', 'segments', and 'mat_peptide' fields.
=> Add/Remove remaining Solr elements to Genome Overview / Sidebar

public/js/p3/WorkspaceManager.js, public/js/p3/widget/ActionBar.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/app/MSA.js, public/js/p3/widget/viewer/File.js, public/js/p3/widget/viewer/TSV_CSV.js
This commit allows file types to be downloaded by default by creating a list of forbidden download types.
=> Changed to forbiddenDownloadTypes to control DWNLD button.

public/js/p3/store/ProteinStructureJsonRest.js, public/js/p3/widget/AdvancedSearch.js, public/js/p3/widget/DataItemFormatter.js, public/js/p3/widget/GlobalSearch.js, public/js/p3/widget/ProteinStructureGrid.js, public/js/p3/widget/ProteinStructureGridContainer.js, public/js/p3/widget/templates/GlobalSearch.html, public/js/p3/widget/viewer/Genome.js, public/js/p3/widget/viewer/ProteinStructureList.js, public/js/p3/widget/viewer/Taxonomy.js, public/js/p3/widget/viewer/_GenomeList.js
This pull request adds the protein structure tab to the taxon view and also adds the protein structure data type to the global search.
=> Protein Structure

public/js/p3/widget/ProteinStructure.js, public/js/p3/widget/ProteinStructureEffect.js, public/js/p3/widget/ProteinStructureHighlight.js, public/js/p3/widget/ProteinStructureSelect.js, public/js/p3/widget/templates/ProteinStructureViewer.html, public/js/p3/widget/viewer/ProteinStructure.js
Adds protein selector
This reverts commit 318fd14da
remove highlights when protein accession changes
=> Allow selecting protein on page

public/js/p3/widget/proteinStructure/ProteinStructure.js, public/js/p3/widget/viewer/ProteinStructure.js
=> use a reduced viewport for Safari

public/js/p3/widget/app/Annotation.js, public/js/p3/widget/app/MetagenomicBinning.js, public/js/p3/widget/app/templates/Annotation.html, public/js/p3/widget/app/templates/MetagenomicBinning.html
Changes to Annotation and Metagenomic Binning UI's.
=> Changes to Features/integration dina fix

public/js/p3/store/SurveillanceJsonRest.js, public/js/p3/widget/DataItemFormatter.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/SurveillanceGrid.js, public/js/p3/widget/SurveillanceGridContainer.js, views/bv-brc-header.ejs
Add Influenza A virus to featured virus list
Add Gene Tree to services menu
Add some Surveillance files; nothing shown but already committed on branch.
=> Integration

app.js, public/js/p3/app/p3app.js, public/js/p3/util/QueryToEnglish.js, public/js/p3/widget/search/GenomeSearch.js, public/js/p3/widget/search/SearchBase.js, public/js/p3/widget/search/templates/GenomeSearch.html, public/js/p3/widget/viewer/GenomeList.js
genome search is available /searches/GenomeSearch
=> advanced search prototype

public/js/p3/widget/app/PrimerDesign.js, public/js/p3/widget/app/templates/PrimerDesign.html
Created the Primer Design service interface. Service help links need to be updated and do not currently work.
=> Added PrimerDesign UI: html and javascript

public/js/p3/widget/app/PrimerDesign.js, public/js/p3/widget/app/templates/PrimerDesign.html
this branch was made off of features/integration with all of the updates that were in the initial pull request
=> Created a new branch from features/integration to push primer design interface changes

public/js/p3/widget/search/GenomeSearch.js, public/js/p3/widget/search/GenomicFeatureSearch.js, public/js/p3/widget/search/HostGroups.js, public/js/p3/widget/search/PathogenGroups.js, public/js/p3/widget/search/templates/GenomeSearch.html, public/js/p3/widget/search/templates/GenomicFeatureSearch.html
new default fields on genome and genome feature search
=> Advanced search

public/js/p3/widget/VariantLineageDetail.js, public/js/p3/widget/templates/VariantLineageOverview.html
Reverts BV-BRC/bvbrc_website#134
=> Revert "Update SARS-CoV-2 VoC/VoI"

public/js/p3/widget/ActionBar.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/app/Annotation.js, public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/Assembly2.js, public/js/p3/widget/app/ComprehensiveGenomeAnalysis.js, public/js/p3/widget/app/GenomeAlignment.js, public/js/p3/widget/app/MetagenomicReadMapping.js, public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/Variation.js, public/js/p3/widget/app/templates/Annotation.html, public/js/p3/widget/app/templates/Assembly2.html, public/js/p3/widget/app/templates/ComprehensiveGenomeAnalysis.html, public/js/p3/widget/app/templates/MetagenomicReadMapping.html, public/js/p3/widget/app/templates/TaxonomicClassification.html
Fixed the issue from the last pull request.
=> Form fill update

public/js/p3/widget/UserSelector.js
Fix for sharing.  Requires updated p3_user.
=> fix sharing for new auth

public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/templates/Homology.html
bug fix: Removing explicit id usage from dojo template. 
feature: Adding loading Gif to lookahead job.
=> template fix and loading gif

public/js/p3/widget/app/Tnseq.js, public/js/p3/widget/app/templates/Tnseq.html
The HTML template is written with new whitespace style, but it should be identical to the old file.
=> Changed reset defaults to prevent primer error.

public/js/p3/widget/DataItemFormatter.js, public/js/p3/widget/search/EpitopeSearch.js
https://github.com/BV-BRC/issues/issues/237
https://github.com/BV-BRC/issues/issues/234
=> beta_v3 commits

public/js/p3/widget/JobManager.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/ComprehensiveSARS2Analysis.js, public/js/p3/widget/app/Expression.js, public/js/p3/widget/app/FastqUtil.js, public/js/p3/widget/app/GeneTree.js, public/js/p3/widget/app/GenomeAlignment.js, public/js/p3/widget/app/MSA.js, public/js/p3/widget/app/MetagenomicBinning.js, public/js/p3/widget/app/PrimerDesign.js, public/js/p3/widget/app/Rnaseq.js, public/js/p3/widget/app/SeqComparison.js, public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/Tnseq.js, public/js/p3/widget/app/Variation.js, public/js/p3/widget/app/templates/Expression.html, public/js/p3/widget/app/templates/SeqComparison.html
Completes FormFilling for all services except Homology, PhylogeneticTree, and MetaCATS
=> Form fill beta v3 clark

views/bv-brc-header.ejs
https://github.com/BV-BRC/issues/issues/251
=> Update doc links to prod docs site

public/js/p3/widget/JobManager.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/MetaCATS.js, public/js/p3/widget/app/PhylogeneticTree.js, public/js/p3/widget/app/templates/PhylogeneticTree.html
This completes Homology and MetaCATS for FormFilling. Only service to be completed with respect to FormFilling is PhylogeneticTree
=> Beta v4 formfill - Clark

public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/MSA.js, public/js/p3/widget/app/templates/Homology.html, public/js/p3/widget/app/templates/MSA.html
Added white space for readability in AppBase.js as well.
=> Refactored and improved FASTA validation for MSA and Homology services.

public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/templates/Homology.html
Reverts BV-BRC/bvbrc_website#261
=> Revert "Made fasta file db JSON consistent with app spec."

public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/templates/Homology.html
Change double quotes to single quotes as well.
=> Fix the fasta file db on the homology service.

public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/templates/Homology.html
Changes:
1. Added feature group to the list of Homology service databases. 
2. Removed the genome list from the genome group submission for Homology.
=> Added the feature group to the Homology service databases

public/js/p3/app/p3app.js
Removed a bit of whitespace as well.
=> Changed the name of some pages to BRC.

public/js/p3/widget/app/GenomeDistance.js, public/js/p3/widget/app/PrimerDesign.js, public/js/p3/widget/app/templates/PrimerDesign.html
=> Added validation after selecting a fasta file

public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/templates/Homology.html
Removing problematic id DOM elements
=> Alpha jan2021 clark blast reload

public/js/p3/widget/AdvancedSearchFields.js, public/js/p3/widget/ColumnsGenome.js, public/js/p3/widget/DataItemFormatter.js, public/js/p3/widget/search/GenomeSearch.js, public/js/p3/widget/search/GenomicFeatureSearch.js, public/js/p3/widget/search/PathwaySearch.js, public/js/p3/widget/search/ProteinFeatureSearch.js, public/js/p3/widget/search/ProteinStructureSearch.js, public/js/p3/widget/search/SerologySearch.js, public/js/p3/widget/search/SpecialtyGeneSearch.js, public/js/p3/widget/search/SubsystemSearch.js, public/js/p3/widget/search/templates/GenomeSearch.html, public/js/p3/widget/search/templates/GenomicFeatureSearch.html, public/js/p3/widget/search/templates/PathwaySearch.html, public/js/p3/widget/search/templates/ProteinFeatureSearch.html, public/js/p3/widget/search/templates/ProteinStructureSearch.html, public/js/p3/widget/search/templates/SpecialtyGeneSearch.html, public/js/p3/widget/search/templates/SubsystemSearch.html, views/home.ejs
**PR:**
- Adv Search 'genome' field changed to range input
- Made doc links on home page open in a new tab
- Removed old unused code on the home page
- Add Genome ID search input to SP Gene Search
- Add Genome ID search input to Protein Search
- Add Genome ID search input to Domain & Motif Search
- Add Genome ID search input to Protein Structure Search
- Add Genome ID search input to Pathway Search
- Add Genome ID search input to Subsystem Search
- Add Genome ID search input to Genome Search
- Remove required fields blocking submit on Subsystem Search
- Removed 'segments' from Genomes tab columns, side detail panal, and adv search
- Added logic for different Serology searches
=> Multiple fixes and added features

public/js/p3/WorkspaceManager.js, public/js/p3/resources/WorkspaceManager.css, public/js/p3/widget/FeatureOverview.js, public/js/p3/widget/GenomeOverview.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/SelectionToGroup.js, public/js/p3/widget/ServicesTooltipDialog.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/app/Homology.js
Filling in temporary feature/genome groups will not work until their respective WorkspaceObjectSelectors work
=> Context based submission iteration 2

public/js/p3/widget/GridContainer.js
=> add grid container menu

public/js/p3/widget/MapsCanvas.js
=> ESLint fixes

public/js/p3/store/HomologyResultMemoryStore.js, public/js/p3/widget/app/FastqUtil.js, public/js/p3/widget/app/Homology.js
Fixes bug introduced in https://github.com/BV-BRC/bvbrc_website/commit/9aae4b859ff0b47e8fc49191abcc9da371bc4aea#diff-142bb70de8d34c715096ca3892a95b917a946f66a900419d80158a3e25cff4a4
for Homology container "view results".
Switches Homology viewer to use sequence id.
Puts paired read filter in fastq-utils
=> Alpha feb2022

package-lock.json
Reverts BV-BRC/bvbrc_website#305
=> Revert "Bump node-fetch from 3.1.0 to 3.2.0"

public/js/p3/widget/WorkspaceFilenameValidationTextBox.js, public/js/p3/widget/WorkspaceObjectSelector.js
The memory store only changes when the workspace changes.
=> Changes WorkspaceObjectSelector objects 

public/js/p3/widget/WorkspaceObjectSelector.js
Remove extra calls to refreshWorkspaceItems.
=> Keep the memory store fixed to the home workspace.

public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/GeneTree.js, public/js/p3/widget/app/PrimerDesign.js, public/js/p3/widget/app/templates/GeneTree.html
=> GeneTree and PrimerDesign Fixes

public/js/p3/widget/Phylogeny2.js
Fix for issue: https://github.com/BV-BRC/issues/issues/635
=> Tweak startup code to get better tip labels. 

public/js/p3/store/IDMappingAppMemoryStore.js, public/js/p3/widget/app/IDMapper.js, public/js/p3/widget/app/templates/IDMapper.html
Adding the ability to bring in multiple genome ids and map them to a list.
=> ID mapper genome id support

public/js/p3/widget/app/templates/MSA.html
This fixes JIRA issue BVBRC-114.
=> Removed unnecessary upload buttons.

public/js/p3/store/TsvCsvMemoryStore.js, public/js/p3/widget/TSV_CSV_Grid.js, public/js/p3/widget/TsvCsvFeatures.js
1. Turn on column headers by default for .snp.tsv files. This fixes issue 1 in https://github.com/BV-BRC/issues/issues/157.
2. Removed an extra blank line at the end of the data store. This fixes issue 3 in https://github.com/BV-BRC/issues/issues/157.
3. Converted numeric columns into numbers so that the TSV viewer sorts numeric columns as numbers rather than strings. This fixes issue 4 in https://github.com/BV-BRC/issues/issues/157.
4. Removed some whitespace from the code for style.
=> Enhancements to the TSV viewer for BV-BRC issue 157.

public/js/p3/widget/app/GeneTree.js, public/js/p3/widget/app/MSA.js
This addresses issues: https://github.com/BV-BRC/issues/issues/723 and https://github.com/BV-BRC/issues/issues/714.
Fixed some whitespace issues.
=> Increased genome size limit to 250k

public/js/p3/app/p3app.js, public/js/p3/widget/JobManager.js, public/js/p3/widget/app/Annotation.js, public/js/p3/widget/app/Assembly2.js, public/js/p3/widget/app/ComprehensiveGenomeAnalysis.js, public/js/p3/widget/app/ComprehensiveSARS2Analysis.js, public/js/p3/widget/app/FastqUtil.js, public/js/p3/widget/app/GeneTree.js, public/js/p3/widget/app/GenomeAlignment.js, public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/MSA.js, public/js/p3/widget/app/MetaCATS.js, public/js/p3/widget/app/MetagenomicBinning.js, public/js/p3/widget/app/MetagenomicReadMapping.js, public/js/p3/widget/app/PhylogeneticTree.js, public/js/p3/widget/app/PrimerDesign.js, public/js/p3/widget/app/Rnaseq.js, public/js/p3/widget/app/SeqComparison.js, public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/Tnseq.js, public/js/p3/widget/app/Variation.js
Had to remove rerun option for some services since their forms have been changed. Need to be updated.
=> Fixing an issue with rerun functionality

public/js/p3/widget/WorkspaceBrowser.js
This addresses issue https://github.com/PATRIC3/patric3_website/issues/2411.
=> Added the genome browser button to FastqUtils.

public/js/p3/widget/app/MetaCATS.js
@chris-c-thomas Fixes issue https://github.com/BV-BRC/issues/issues/292 for workshop next week
=> fixing issues with pulling in feature group numbers

public/js/p3/widget/UserProfileForm.js
Fix issue reporting errors during profile update. Specifically email address conflicts.
=> Report error for email conflict when changing

public/js/p3/store/ProteinFamiliesServiceMemoryStore.js, public/js/p3/widget/ProteinFamiliesServiceHeatmapContainer.js
fixing multiple pop-up bug in protein families viewer. the pop-up still occurs at incorrect times
=> Alpha august2022 clark comparativesystems

public/js/p3/app/app.js, public/js/p3/app/p3app.js
- Auto refresh user profile when page loads
- Fix warnings coming from intercepting twitter messages in app.
=> - Fix error message coming from twitter onMessage.

public/js/p3/widget/Phylogeny2.js
https://github.com/BV-BRC/issues/issues/876
=> enhancement: activate genome_name as a valid label on Archaeopteryx trees

app.js, public/js/p3/app/app.js, views/header.ejs, views/javascript.ejs
This forces css and js loaded from javascript.ejs and header.ejs to work with version urls like the normal patric code.
=> 3rd part library versioned requests

public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/viewer/MSATree.js
https://github.com/BV-BRC/issues/issues/890
=> Added the tree panel to the workspace MSA viewer

public/js/p3/widget/TsvCsvFeatures.js, public/js/p3/widget/viewer/TSV_CSV.js
This partially fixes https://github.com/BV-BRC/issues/issues/879.
The error message will tell the user if the file is too big for the viewer. I set it to 150 MB.
=> Increased the TSV viewer limit and added an error message.

public/js/p3/store/TsvCsvMemoryStore.js, public/js/p3/widget/viewer/TSV_CSV.js
This addresses https://github.com/BV-BRC/issues/issues/732.
=> Added exact, fuzzy, and range filters to the TSV viewer.

CHANGELOG.md, package.json, public/js/p3/widget/app/ComprehensiveSARS2Analysis.js, public/js/p3/widget/app/templates/ComprehensiveSARS2Analysis.html
* [Feature] SARS-CoV-2 CGA - Add logic for additinal primers to populate version dropdown with correct options
* [Feature] Added exact, fuzzy, and range filters to the TSV viewer.
=> Alpha sept2022

public/js/p3/widget/Phylogeny2.js, public/js/p3/widget/viewer/MSATree.js
Removed URI encode for bread-crumbs path. Also provided a link to the contained job result folder.
https://github.com/BV-BRC/issues/issues/543
=> bug fix: need to remove URI encode for bread-crumbs path display

public/js/p3/widget/PathwayServiceGrid.js, public/js/p3/widget/PathwaysServiceContainer.js, public/worker/PathwayServiceWorker.js
Fixing ec table and removing unnecessary element removal
=> Alpha sept2022 clark comparativesystes

public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/MSA.js, public/js/p3/widget/app/templates/MSA.html
This addresses issue: https://github.com/BV-BRC/issues/issues/158
This front end is for working with the changes to the backend found in https://github.com/BV-BRC/p3_msa/pull/12.
=> Added fields for choosing a reference sequence.

public/js/p3/widget/JobManager.js, public/js/p3/widget/RerunUtility.js, public/js/p3/widget/WorkspaceBrowser.js
Enables the rerun button for Workspace objects in the WorkspaceBrowser.
Abstracts the code from the JobManager into a new file called RerunUtility.
Some linting.
=> Enabled rerun for the Workspace.

public/js/p3/widget/viewer/TSV_CSV.js
This enhances the TSV viewer so that the user can select more than 25 features. This is useful for comparative systems.
=> Increased the features queried. Targeted a blank page.

public/js/p3/widget/WorkspaceBrowser.js
This fixes the bug in https://github.com/BV-BRC/issues/issues/645.
=> Base the alignType on the afa file for the MSA viewer.

public/js/p3/widget/app/FastqUtil.js, public/js/p3/widget/app/templates/FastqUtil.html
This fixes issue: https://github.com/BV-BRC/issues/issues/932
Improved the style of the html.
=> Changed error message to say Fastq Utilities.

public/js/p3/widget/app/AppBase.js
This addresses issue https://github.com/BV-BRC/issues/issues/660
=> Test for DNA by looking at frequency of ACTGN.

public/js/p3/widget/GridContainer.js
[#943](https://github.com/BV-BRC/issues/issues/943#issuecomment-1297829211)
=> bug fix for viewing fasta dna&proteins in GenomeList

public/js/p3/widget/GridContainer.js
Reverts BV-BRC/bvbrc_website#451
=> Revert "bug fix for viewing fasta dna&proteins in GenomeList"

public/js/p3/widget/app/MSA.js, public/js/p3/widget/app/templates/MSA.html
This incorporates some feedback from the technical call a week ago.
=> Added genome id and FilteringSelect for feature id.

public/js/p3/app/p3app.js
1. Removed repeated message that was filling up the console: console.log('checking for login');
2. Commented out two unused variables
3. Ran the code through eslint
=> Removed repeating login message. Lint and style enhanced.

public/js/p3/store/SubsystemServiceMemoryStore.js, public/js/p3/store/SubsystemServiceOverviewMemoryStore.js, public/worker/SubsystemServiceWorker.js
Don't deploy until the next alpha container please!
=> Updating subsystems data loading to be compatible with backend

public/js/p3/widget/viewer/GenomeAlignment.js
This requires the mauve_viewer submodule rebuild.
=> Move the save button from outside to inside of the viewer. 

public/js/p3/store/HomologyResultMemoryStore.js, public/js/p3/widget/HomologyResultGrid.js
When the memory store is trying to load something, it says 'loading'
When there is nothing to load, it says there are no results.
=> Changed the loading message when there is no data.

public/js/p3/widget/SubsystemServiceMapContainer.js, public/js/p3/widget/SubsystemServiceMemoryGridContainer.js, public/js/p3/widget/viewer/SubsystemServiceMap.js
Fixed a bug in loading the subsystems heatmap, adds a couple files to support this
=> testing solution to subsystems heatmap loading issue

public/js/p3/widget/app/ComparativeSystems.js, public/js/p3/widget/app/GenomeDistance.js, public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/MSA.js, public/js/p3/widget/app/SubspeciesClassification.js, public/js/p3/widget/app/templates/AppLogin.html, public/js/p3/widget/app/templates/ComparativeSystems.html, public/js/p3/widget/app/templates/GenomeDistance.html, public/js/p3/widget/app/templates/Homology.html, public/js/p3/widget/app/templates/SubspeciesClassification.html
This fixes issue https://github.com/BV-BRC/issues/issues/957.
Reworded the login message to refer to PATRIC and ViPR/IRD as well as BV-BRC.
=> Added the login page to services that missed it.

public/js/p3/widget/app/templates/MetaCATS.html
This fixes issue https://github.com/BV-BRC/issues/issues/964.
=> Changed ids for navigation.

public/js/p3/widget/app/MetagenomicBinning.js, public/js/p3/widget/app/templates/MetagenomicBinning.html
Allow disabling mobile element screen
Allow setting minimum contig coverage and length.
=> Add advanced binning parameters

public/js/p3/widget/RerunUtility.js, public/js/p3/widget/app/SubspeciesClassification.js
https://github.com/BV-BRC/issues/issues/970
=> add rerun ability to subspecies classification service

public/js/p3/widget/app/Homology.js, public/js/p3/widget/app/templates/Homology.html
This fixes https://github.com/BV-BRC/issues/issues/374 and https://github.com/BV-BRC/issues/issues/614.
=> Added contigs to database and query sources.

public/js/p3/widget/GenomeDistanceResultGrid.js
=> adding genome status and quality as displayed in similar genome finder

public/js/p3/widget/app/templates/MetagenomicBinning.html
We should have a standard config mechanism to set these defaults rather than have them embedded in the templates.
=> Change default binning threshold to match assembly app

public/js/p3/widget/Phylogeny2.js
https://github.com/BV-BRC/issues/issues/543
=> Include the name of the tree file in the bread crumbs

public/js/p3/widget/WorkspaceBrowser.js
See https://github.com/BV-BRC/issues/issues/993
=> Enhancement for viewing nwk and phyloxml files

public/js/p3/widget/WorkspaceBrowser.js
Fixed initial value for labelSearch.
=> Enhancement for viewing nwk and phyloxml files.

public/js/p3/widget/app/SubspeciesClassification.js, public/js/p3/widget/viewer/PhylogeneticTree2.js
Labels are a bit long and I am looking into other options. 
https://github.com/BV-BRC/issues/issues/972
=> update on subspecies class service

public/js/p3/widget/Phylogeny2.js
https://github.com/BV-BRC/issues/issues/1005.
If the gene tree nodes are feature type and the node ids are either patric_ids or feature_ids, the selected features can be viewed and grouped.
=> Bug fix: Need to be able to create a feature group after selecting the leaves in a particular node on Gene Tree

public/js/p3/widget/viewer/SurveillanceDataMap.js
https://github.com/BV-BRC/issues/issues/1022
=> increase limit to 5k for surveillance map

public/js/archaeopteryx/archaeopteryx-dependencies/canvg.js, public/js/bundle/bundle2.js, public/js/bundle/make_bundle2.sh
For https://github.com/BV-BRC/issues/issues/1033
- Added this version of [canvg](https://github.com/cmzmasek/archaeopteryx-js/blob/master/dependencies/canvg.js) to dependency folder
- Enabled it in `make_bundle2.sh`
- Reran the bundle script for a new `bundle2.js` that now includes `canvg.js` for the PNG export feature.
=> Archaeopteryx PNG Export

public/js/bundle/make_bundle2.sh
https://github.com/BV-BRC/issues/issues/1033
=> Included rgbcolor.js to fix the download png bug

package.json
=> Revert "Bump version to 3.28.22"

public/js/p3/widget/app/templates/MetagenomicReadMapping.html
=> Revert "Update MetagenomicReadMapping.html"

public/js/p3/widget/GenomeOverview.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/ServicesTooltipDialog.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/app/MSA.js
Submitting BLAST jobs from genome overview, genome group, genome list, feature group, and feature list context are set up. Still need to discuss a default job submission location
=> Reworking some context submission stuff

public/js/p3/widget/app/templates/SequenceSubmission.html
=> update sequence submission ui for required fields and supported virus info

package.json
=> Alpha => Beta final update

public/js/p3/widget/viewer/MSAView.js
https://github.com/BV-BRC/issues/issues/1177
=> MSA viewer: Add h1_clade_global,h1_clade_us,h3_clade,h5_clade metadata to ID type drop down list

public/js/p3/widget/viewer/PhylogeneticTree2.js
remove replace regex from tree data as it is taken care of by the backend service
=> remove replace that causes the slowdown

public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/templates/TaxonomicClassification.html
Reverts BV-BRC/BV-BRC-Web#620
It was made to beta not alpha
=> Revert "Beta"

public/js/p3/widget/app/AppBase.js
alpha was missing the changes to AppBase.js for sample ids
originally Nicole's PR but we fixed it to remove inadvertent changes to other code.
=> Update AppBase.js for sample ids

public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/templates/TaxonomicClassification.html
Hello,
These commits add confidence interval options to the 
Changes to backend are captured in PR #22 against https://github.com/BV-BRC/bvbrc_taxonomic_classification_2.
=> update for saving classified/unclassified sequences and flexible confidence interval

public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/templates/TaxonomicClassification.html
=> Revert "update for saving classified/unclassified sequences and flexible confidence interval"

public/js/p3/widget/app/PhylogeneticTree.js, public/js/p3/widget/app/templates/GeneTree.html, public/js/p3/widget/app/templates/PhylogeneticTree.html, public/js/p3/widget/app/templates/ViralGenomeTree.html
Adding genome/feature group options to the tree services and temporarily disabling viral genome restrictions for phylogenetic tree
=> Alpha clark compsystems genetree

public/js/p3/widget/ProteinFamiliesServiceFilterGrid.js
disabling unused columns in protein families sort, adding genome group column
=> adjusting protein families heatmap filter columns

public/js/p3/widget/app/PhylogeneticTree.js
adding some checks to phylogenetic tree to avoid errors
=> adding some checks to phylogenetic tree

public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/templates/TaxonomicClassification.html
Hello Bob,
This should push into ALPHA.
These are the front end changes we discussed on Skype
I put the new feature message in its own commit because it is separate from the drop downs/job submission parameters, we might not put it into production and ultimately we plan to remove it.
Let me know if you have any questions.
Nicole
=> 16s changes

public/js/p3/widget/app/templates/TaxonomicClassification.html
This code should be the 16s_changes branch of my repo going into the alpha branch of the BVBRC repo.
Changes:
Remove break after label
Move blinking message
add info buttons to parameter options
Thank you!
=> Add info buttons to every parameter

public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/templates/TaxonomicClassification.html
!! This should merge into ALPHA !!
Hello Bob, This shouldn't impact anything else.
Kind regards,
Nicole
=> Update to selected libraries box size for taxonomic classification submission page

public/js/p3/widget/ProteinFamiliesHeatmapContainerNew.js, public/js/p3/widget/ProteinFamiliesServiceHeatmapContainer.js
changing labels while heatmap is flipped is broken, will fix that next
=> Fixing flipping heatmap

public/js/p3/widget/app/PhylogeneticTree.js
removing genome groups from metadata dropdown
=> Codon tree update

views/bv-brc-footer.ejs
https://github.com/BV-BRC/issues/issues/1298
=> update youtube url

public/js/p3/store/SubsystemMapMemoryStore.js, public/js/p3/widget/PathwayServiceGrid.js, public/js/p3/widget/SubSystemsMemoryGridContainer.js, public/js/p3/widget/SubsystemGrid.js, public/js/p3/widget/SubsystemMapHeatmapContainer.js, public/js/p3/widget/SubsystemServiceContainer.js, public/js/p3/widget/SubsystemServiceMemoryGridContainer.js, public/js/p3/widget/viewer/SubSystemMap.js
- removed reference genome button and functionality from the subsystems heatmap
- modified the gene conservation column label for pathways
- Added gene conservation and role conservation columns to Subsystems
=> Fixes to Pathways and Subsystems in Comparative Systems

public/js/p3/store/PathwayMapMemoryStore.js, public/js/p3/widget/PathwayMapContainer.js, public/js/p3/widget/PathwayMapHeatmapContainerNew.js, public/js/p3/widget/viewer/PathwayMap.js, public/js/p3/widget/viewer/SubsystemServiceMap.js
- added cluster button to pathways heatmap
- added sort button to pathways heatmap
=> Pathway Cluster and Sort buttons

public/js/p3/widget/app/Annotation.js, views/pages/tools.ejs
=> bug fix typo 

public/js/p3/store/PathwayMapMemoryStore.js, public/js/p3/store/SubsystemMapMemoryStore.js, public/js/p3/widget/SubsystemMapHeatmapContainer.js, public/js/p3/widget/viewer/PathwayMap.js, public/js/p3/widget/viewer/SubSystemMap.js, public/js/p3/widget/viewer/SubsystemServiceMap.js
- Fixing taxonomic sorting for Pathways heatmap
- Fixing taxonomic sorting for Subsystems heatmap
=> Fixing sorting for pathways and subsystems

views/pages/team.ejs
Hello,
Updating the personnel in regard to git issue
[Update personnel on team's page #1247](https://github.com/BV-BRC/issues/issues/1247).  I reviewed the other subgroups and don't see anyone to add or remove - let me know if I missed anyone! If I don't hear anything I'll close the issue. 
Nicole
=> add Nicole Bowers to ANL team

views/pages/team.ejs
Hello, just a quick change to put the ANL team in alphabetical order.
Nicole
=> Put ANL team in alphabetical order

public/js/p3/widget/SubsystemServiceContainer.js
- Fixing variant column, updating to correct backend field name and formatting number to two decimal places
=> Subsystems Column bug fix

public/js/p3/widget/WorkspaceObjectSelector.js
Default object selector to home dropdown.
=> workspace object selector

public/js/p3/widget/GridContainer.js, public/js/p3/widget/viewer/SurveillanceDataMap.js
=>  update surveillance map selection to display up to 750 locations

public/js/p3/widget/Phylogeny.js
https://github.com/BV-BRC/issues/issues/1316
=> Font size changes for the taxon trees on Phylogeny tab

public/js/p3/widget/Phylogeny.js
https://github.com/BV-BRC/issues/issues/1319
=> Display style bug fix for the taxon tree control panels on Phylogeny tab

public/js/p3/widget/Phylogeny.js
- Updating date variable to reset taxon trees
=> updating taxon trees

public/js/p3/widget/RerunUtility.js, public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/templates/TaxonomicClassification.html
- fixing taxonomic classification rerun functionality
=> Alpha clark rerunfixes

public/js/p3/widget/FilterContainerActionBar.js
- Fixing subsystems keyword filter: will now filter while input as input changes
=> adding intermediate changes to subsystems keyword filter

public/js/p3/widget/app/templates/GenomeAlignment.html
https://github.com/BV-BRC/issues/issues/1330
=> Fix bugs in the GenomeAlignment submission form

public/js/p3/widget/app/templates/ComparativeSystems.html, public/js/p3/widget/app/templates/GenomeDistance.html
https://github.com/BV-BRC/issues/issues/1340
=> Add i and ? buttons in the ComparativeSystems submission form

public/js/p3/widget/app/templates/HASubtypeNumberingConversion.html, public/js/p3/widget/app/templates/IDMapper.html, public/js/p3/widget/app/templates/MSA.html, public/js/p3/widget/app/templates/MetaCATS.html, public/js/p3/widget/app/templates/PrimerDesign.html, public/js/p3/widget/app/templates/SequenceSubmission.html, public/js/p3/widget/app/templates/SubspeciesClassification.html
Add additional info buttons for the following service submission forms
HASubtypeNumberingConversion
IDMapper
MSA
MetaCATS
PrimerDesign
SequenceSubmission
SubspeciesClassification
=> Add additional info buttons for several service submission forms

public/js/p3/widget/GridContainer.js, public/js/p3/widget/search/SurveillanceSearch.js
…user to the map BV-BRC/issues#554
=> enhancenment & bug fix for surveillance

public/js/p3/widget/app/SARS2Wastewater.js, public/js/p3/widget/app/templates/SARS2Wastewater.html
Hello Bob,
I have changed the UI code to make the following changes suggested by Maulik:
1. Remove the taxonomy selection in favor of the regular output box.
2. Move sample id and sample date below the primer selection.
Kind regards,
Nicole
=> Changes to the SARS-Cov-2 Wastewater front end

public/js/p3/widget/app/FastqUtil.js
=> Revert "Add scrub human to pipeline selection."

public/js/p3/widget/app/SARS2Wastewater.js
Hello Bob,
Thank you for catching the directory name. I'm sending another PR with the addition of .MD to the quick reference file.
Kind regards,
Nicole
=> Update to tutorial path in SARS2Wastewater.js

package-lock.json, package.json
=> Revert "Bump ejs from 2.7.4 to 3.1.10"

public/js/p3/widget/outbreaks/H5N1/index.js
=> filter out google news items before 2023 and sort them by pubDate

package-lock.json, package.json, public/js/bundle/bundle2.js, public/js/p3/widget/PageGrid.js, public/js/p3/widget/app/Docking.js, public/js/p3/widget/outbreaks/H5N1/index.js, public/js/p3/widget/outbreaks/OutbreaksGeoMap.html, public/js/p3/widget/outbreaks/OutbreaksGeoMap.js, public/js/p3/widget/outbreaks/OutbreaksGeoMapInfo.html, public/js/p3/widget/outbreaks/OutbreaksGeoMapInfo.js
Due to the cherry-picked updates had to do this merge via an auxiliary branch.
=> Production update from alpha/beta via merge branch

public/js/p3/widget/RerunUtility.js, public/js/p3/widget/app/Docking.js, public/js/p3/widget/app/templates/Docking.html, public/js/p3/widget/app/templates/TaxonomicClassification.html, views/bv-brc-header.ejs
Hello,
Below are changes encapsulated in this request:
- Move the docking service to the bottom of the protein tools
- Enable the docking rerun button
- Remove the blinking read message about the new 16S support for Taxonomic Classification
Kind regards,
Nicole
=> UI Updates for Docking service and TC clean up

public/js/p3/widget/app/Docking.js, public/js/p3/widget/app/templates/Docking.html
Hello Bob,
Let me know if there any issues with these changes. They are working in my local instance.
Kind regards,
Nicole
=> Alpha - Docking update to add the PDB upload and preview 

public/js/p3/widget/app/Docking.js, public/js/p3/widget/app/templates/Docking.html
=> aligning the pdb input file preview button with the workspace file selection field.

public/js/p3/WorkspaceManager.js
Per request at development meeting
=> updating to give PDB type updload

public/js/p3/widget/app/TaxonomicClassification.js
Hello Bob, 
Thank you for reviewing this PR.
The changes are in regard to git issue [1309](https://github.com/BV-BRC/issues/issues/1309) - Clark did the majority of the work adding the rerun button. I am updating the rerun button to include the missing (and final) parameters: save classified and unclassified sequences.
These changes are tested locally and ready for alpha.
Kind regards,
Nicole
=> update to the taxonomic classification rerun button

public/js/p3/widget/AMRPanelMetaSummary.js
Update the data processing to parse the new structure of pivot facet from solr9
=> Bug fix: AMR panel on taxon overview page

public/js/p3/widget/FacetFilter.js
=> Revert "facet fix"

views/pages/team.ejs
The changes in this pull request include:
- The addition of the UIC team
- The addition of the UIC team logo from the official branding page
- Moving Clark C. from the UVA team to the ANL team
=> Update to teams page

public/js/p3/resources/bv-brc.css, public/js/p3/widget/AdvancedSearch.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/viewer/Serology.js, public/js/p3/widget/viewer/Surveillance.js
- Fixed displaying surveillance and serology search and detail pages
- Updated outbreak image margins on homepage for medium screen sizes
=> Fix search/detail page for surveillance and serology and adjust homepage outbreak image margins

public/js/p3/widget/app/CoreGenomeMLST.js, public/js/p3/widget/app/WholeGenomeSNPAnalysis.js, public/js/p3/widget/app/templates/CoreGenomeMLST.html, public/js/p3/widget/app/templates/WholeGenomeSNPAnalysis.html
Hello Bob! These changes are not submitting on local. Let's work together to make sure it will submit on alpha. I'll message you on slack.
Nicole
=> add flexible thresholds and other website improvements

public/js/p3/widget/app/TreeSort.js, public/js/p3/widget/app/templates/TreeSort.html
- Improved the formatting of the advanced options checkbox rows and added info icons.
- The submit button now disables itself after it's clicked.
=> Updates to TreeSort checkbox row formatting and submit button behavior

public/js/p3/widget/app/templates/Assembly2.html, public/js/p3/widget/app/templates/CoreGenomeMLST.html, public/js/p3/widget/app/templates/WholeGenomeSNPAnalysis.html
Hello Bob,
This is the fix I needed for the genome input pages.
This also includes updates to the assembly page for Allan.
Thank you for your help setting up the local doc site.
Kind regards,
Nicole
=> Nb alpha 07 01 2025

public/js/p3/widget/app/SARS2Wastewater.js, public/js/p3/widget/app/WholeGenomeSNPAnalysis.js, public/js/p3/widget/app/templates/SARS2Wastewater.html
This PR is to update the covid waste water service for the new primers added by this [PR]( https://github.com/BV-BRC/primer-schemes/pull/2). 
Also, a update to the whole genome SNP tutorial path commit snuck in that appears to already be on alpha? I do not expect it to cause any issues though.
=> Alpha nb 06 27 2025

public/js/p3/widget/app/TreeSort.js, public/js/p3/widget/app/templates/TreeSort.html
- Updated CSS classes in TreeSort.html to be more consistent with other BV-BRC templates.
- Removed the "is time scaled" checkbox.
- Removed the redundant submit event handler as it is likely responsible for a submission error on the alpha server.
=> Removed a checkbox, made CSS consistent with other templates, removed redundant submit handler

public/js/p3/widget/app/Annotation.js, public/js/p3/widget/app/Assembly.js, public/js/p3/widget/app/Assembly2.js, public/js/p3/widget/app/GenomeDistance.js, public/js/p3/widget/app/MetagenomicBinning.js, public/js/p3/widget/app/MetagenomicReadMapping.js, public/js/p3/widget/app/PhylogeneticTree.js
The following updates were made:
Genome Assembly: https://youtube.com/playlist?list=PLWfOyhOW_Oat3lYK7hXorV9jPZxgwBw32&si=L0ApfPQlx-65230D
Genome Annotation: https://youtube.com/playlist?list=PLWfOyhOW_Oav3zsNKRx_4EMJQjvY7q_U3&si=pg4jREU2MFY_-PBW
Similar Genome Finder: https://youtube.com/playlist?list=PLWfOyhOW_OashHfld0w1DUkO7rQz6s8SA&si=Enh6GME_i4LMcXL8
Bacterial Genome Tree: https://youtube.com/playlist?list=PLWfOyhOW_Oavr0PDosswbQ6tfHBLCMBXZ&si=Tb61muJUHjiWrkaK
Metagenomic Binning: https://youtube.com/playlist?list=PLWfOyhOW_OasTc7mmLSXZvQYrO_R5se47&si=X66tQsvWsW0GuA6Z
Metagenomic Read Mapping: https://youtube.com/playlist?list=PLWfOyhOW_Oaurdhs675JawVb4LIcAncKc&si=TK4xGmL_92kiiHDG
=> Updated YouTube links with Rebecca's new tutorials
